Update main.yaml

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -1,4 +1,3 @@
-
 on:
   push:
     branches:
@@ -55,6 +54,27 @@ jobs:
     steps:
       - name: Checkout Code
         uses: actions/checkout@v3
+
+      - name: Ensure unzip is installed
+        run: |
+          if ! command -v unzip &> /dev/null; then
+            echo "unzip not found. Installing..."
+            sudo apt-get update
+            sudo apt-get install -y unzip
+          else
+            echo "unzip already installed."
+          fi
+
+      - name: Ensure AWS CLI is installed
+        run: |
+          if ! command -v aws &> /dev/null; then
+            echo "AWS CLI not found. Installing..."
+            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+            unzip awscliv2.zip
+            sudo ./aws/install
+          else
+            echo "AWS CLI already installed."
+          fi
 
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v4
